### ISSUE TITLE
Inconsistent DLL state after inserting repeated poll id

### ISSUE THREAD

**Issue by medvedev1088** [skmgoldin/tcr#1]
Steps to reproduce: 
1. Start 2 polls: with ids 1 and 2.
2. Call PLCRVoting.commitVote(1, \<secretHash1\>, 7, 0). Actual vote inside the hash doesn't matter, can be 0 or 1.
3. Call PLCRVoting.commitVote(2, \<secretHash2\>, 8, 1). 
4. Call PLCRVoting.commitVote(1, \<secretHash3\>, 9, 2). 
5. Call PLCRVoting.getInsertPointForNumTokens(\<yourAddress\>, 6).
Expected result: 0. 
Actual result: infinite loop/out of gas.

Here is a test case demonstrating this issue https://github.com/skmgoldin/tcr/pull/2

![dll bug 3](https://user-images.githubusercontent.com/930603/34392746-c4eb38b2-eb80-11e7-914b-b8d1efa9f46b.png)

**Comment by skmgoldin** [comment]
I'm going to review this all carefully next week, including your patches, and will be in touch about what we do next.

Thanks for reporting this and for the pull requests. I actually had been aware of a bug here, but it's a little hairier than I thought it was. The AdToken bug bounty is technically over, but I want to thank you for discovering this and reporting it so thoroughly. If you send me an Ethereum address, I'll send you 10,000 AdToken. :)

**Comment by medvedev1088** [comment]
@skmgoldin wow, that's a huge reward. Thanks a lot! My Ethereum address is 0xEda5Bbd45681a1c07EeAfd89692c41ca060E84d2. Looking forward to working together on this :)

**Comment by cemozerr** [comment]
Great catch and fix @medvedev1088! Also, I really like the addition of getStart/End functions. There might be other use cases of these functions for other contracts calling the DLL library.

**Comment by skmgoldin** [comment]
@medvedev1088 https://etherscan.io/tx/0x84624050aa00761a77e7d455c24949dc0d14646bda2430efad2eea13b70c39aa
