### ISSUE TITLE
Use "tokens/eip20/EIP20Interface.sol" instead of "tokens/eip20/EIP20.sol"

### ISSUE THREAD

**Issue by suhabe** [skmgoldin/tcr#25]
If PLCRVoting, Parameterizer, and Registry work with any EIP20 token, use the EIP20Interface type rather than ConsenSys's specific implementation of it.

**Comment by kangarang** [comment]
https://github.com/skmgoldin/tcr/commit/d735858c81297d597d335779e50a5f2baa729cce
