### ISSUE TITLE
Integer overflow in Registry.apply

### ISSUE THREAD

**Issue by niran** [skmgoldin/tcr#27]
`listingHash.applicationExpiry = block.timestamp + parameterizer.get("applyStageLen")` can overflow.

**Recommendation**

Use SafeMath for arithmetic. If the token holders set `applyStageLen` too high, all new applications will revert until they pass a proposal to change the setting.

**Comment by kangarang** [comment]
https://github.com/skmgoldin/tcr/commit/9d8b7af5fef7516dd6f84dfdce4f05109cae4a7e
