### ISSUE TITLE
An unchallenged application cannot be cancelled

### ISSUE THREAD

**Issue by niran** [skmgoldin/tcr#28]
Whitelisted applicants can exit the registry when they discover new information that threatens their deposit. New applicants cannot do so because `exit` calls `require(isWhitelisted(_listingHash))`. Even without an active challenge, a new applicant with new information cannot protect themselves from a challenge the way whitelisted applicants can.

**Recommendation**

If this is desired behavior, keep it. Just pointing out the discrepancy.

**Comment by skmgoldin** [comment]
We decided to not deal with this, and will document it.
