### ISSUE TITLE
Parameterizer proposal owner never gets token back if proposal goes unchallenged

### ISSUE THREAD

**Issue by mnoster** [skmgoldin/tcr#30]
When a user submits a proposal and it goes unchallenged, the user does not get their token back after the `processProposal` function is invoked.

In the `processProposal` function in the first condition `if(canBeSet(_propID))` the value is being set but the token is never transferred back to the owner.

There should be a `token.transfer` within this condition.

Tokens are being locked in contract.

https://github.com/skmgoldin/tcr/blob/master/contracts/Parameterizer.sol#L221

**Comment by skmgoldin** [comment]
This is a real bug!
