### ISSUE TITLE
Parameterizer: Add _RewardClaimed(msg.sender, _challengeID, reward)

### ISSUE THREAD

**Issue by eccheung4** [skmgoldin/tcr#34]
Add _RewardClaimed(msg.sender, _challengeID, reward) to Parameterizer.sol claimVoterReward function similiar to Registry.sol event https://github.com/skmgoldin/tcr/blob/master/contracts/Registry.sol#L281

**Comment by kangarang** [comment]
Resolved: 6d3eac7a54209dad485454bf26a907e1151b2d29
