### ISSUE TITLE
[question] use of masterCopy

### ISSUE THREAD

**Issue by ya7ya** [skmgoldin/tcr#36]
Hello, 

I was wondering what's the use of `masterCopy` var that's used in all 3 contracts ? i'm guessing it's for creating copies of contracts safely as mentioned here https://github.com/ethereum/solidity/issues/2296

if so, my noob questions are: 
- How does someone create a copy of the contract using this method? 
- Where is `masterCopy` set ? I looked at `setup` and the constructor but can't seem to find it. I also looked at the tests but couldn't find that out.

I appreciate you taking the time to answer these questions. and I do apologize if they seem like simple questions 🙇 😄 

Cheers.

**Comment by Kmoneal** [comment]
This issue pertains to the [master-deprecated](https://github.com/skmgoldin/tcr/tree/master-deprecated) branch utilizing a proxy contract implementation. If you would like to learn more about the proxy contract deployment contract, checkout [gnosis-safe-contracts](https://github.com/gnosis/gnosis-safe-contracts).
