### ISSUE TITLE
Request: Standard Data Formatting for TCR Meta Data

### ISSUE THREAD

**Issue by SilentCicero** [skmgoldin/tcr#44]
Hey all,

While parsing and handling TCR data I came across a bit of a need to have some standards or "suggested standards" around TCR data. Below I want to walk through some potential examples, and ideas around standard TCR data formatting.

## Motivation
Many apps and systems will need some kind of standard API or data format to fallback on for some data primitives. It would be nice to have some basic suggested standards around this to simplify third-party system architecture.

#### Description
The plaintext option is simply the data in question and does not need to be formatted.

#### Examples:
data => "nick.com"
data => "MyNameIsThis"
data => "Hello world"

#### Description
This option describes an IPFS hash, which should lead to a reducible JSON data schema

#### Examples:
data => QmTp2hEo8eXRp6wg7jXv1BLCMh5a4F3B7buAUZNZUu772j

JSON Data Format:
QmTp2hEo8eXRp6wg7jXv1BLCMh5a4F3B7buAUZNZUu772j => 
```json
{
    "title": "My application title",
    "name": "Data Name",
    "description": "My application description",
    "shortDescription": "My short application description",
    "content": "My application content"
}
```

JSON Schemas can follow some existing standards if possible:
Products: http://schema.org/Product
Persons: http://schema.org/Person
Offers: http://schema.org/Offer
Buisineses: http://schema.org/LocalBusiness

Thoughts welcome!

**Comment by kangarang** [comment]
related: #7

**Comment by kangarang** [comment]
i implemented a tcr of tcrs on ipfs recently

the master tcr is a list of:
  "high-quality tcrs that compile to the master tcr's abis"

```js
const abis = {
  id: "Prospect Park",
  registry: {
    abi: [{}, {}],
    bytecode: "0x60606060...",
    contractName: "Registry",
    networks: {
      "4": "0x123456789...",
      "420": "0x420420420..."
    }
  },
  token: {
    abi: [{}, {}],
    bytecode: "0x60606060...",
    contractName: "EIP20Interface",
    networks: {
      "4": "0x123456789...",
      "420": "0x420420420..."
    }
  },
  voting: {
    abi: [{}, {}],
    bytecode: "0x60606060...",
    contractName: "PLCRVoting",
    networks: {
      "4": "0x123456789...",
      "420": "0x420420420..."
    }
  },
  parameterizer: {
    abi: [{}, {}],
    bytecode: "0x60606060...",
    contractName: "Parameterizer",
    networks: {
      "4": "0x123456789...",
      "420": "0x420420420..."
    }
  },
}
const listingHash = keccak256(abis.id)
const multihash = ipfs.add(abis)

registry.apply(listingHash, numTokens, multihash)
```

a ui can generate contract abstractions and apply/challenge/vote for tcrs that should be whitelisted.

the ui can select a whitelisted tcr, which will trigger the ui to render the selected tcr's listings

```js
const tcr = {
  id: "0x2537a44f139dde706126d1c5947945daf999dc3f"
}
const listingHash = keccak256(tcr.id)
const multihash = ipfs.add(tcr)

registry.apply(listingHash, numTokens, multihash)
```

would love feedback!
