### ISSUE TITLE
Discussion: Event changes

### ISSUE THREAD

**Issue by kangarang** [skmgoldin/tcr#46]
## REGISTRY

`_Application`: add `appEndDate`

`_Challenge`: remove `deposit`, add `challenger`, change `pollID` to `challengeID`

`_NewListingWhitelisted`: change to `_ApplicationWhitelisted`

Add: (#35 & #45) 
- `_ListingWithdrawn(bytes32 listingHash);`
- `_TouchAndRemoved(bytes32 listingHash);`

Current Implementation:
```sol
event _Application(bytes32 listingHash, uint deposit, string data);
event _Challenge(bytes32 listingHash, uint deposit, uint pollID, string data);
event _Deposit(bytes32 listingHash, uint added, uint newTotal);
event _Withdrawal(bytes32 listingHash, uint withdrew, uint newTotal);
event _NewListingWhitelisted(bytes32 listingHash);
event _ApplicationRemoved(bytes32 listingHash);
event _ListingRemoved(bytes32 listingHash);
event _ChallengeFailed(uint challengeID);
event _ChallengeSucceeded(uint challengeID);
event _RewardClaimed(address voter, uint challengeID, uint reward);
```

Proposed implementation:
```sol
* event _Application(bytes32 listingHash, uint deposit, uint appEndDate, string data);
* event _Challenge(bytes32 listingHash, address challenger, uint challengeID, string data);
  event _Deposit(bytes32 listingHash, uint added, uint newTotal);
  event _Withdrawal(bytes32 listingHash, uint withdrew, uint newTotal);
* event _ApplicationWhitelisted(bytes32 listingHash);
  event _ApplicationRemoved(bytes32 listingHash);
  event _ListingRemoved(bytes32 listingHash);
+ event _ListingWithdrawn(bytes32 listingHash);
+ event _TouchAndRemoved(bytes32 listingHash);
  event _ChallengeFailed(uint challengeID);
  event _ChallengeSucceeded(uint challengeID);
  event _RewardClaimed(address voter, uint challengeID, uint reward);
```

---

## PARAMETERIZER

Add: (#34)
- `_RewardClaimed(msg.sender, _challengeID, reward);`

Add: (#33)
- `_ProposalAccepted(bytes32 propID);` 
- `_ProposalUnprocessed(bytes32 propID);`
- `_ChallengeSucceeded(uint challengeID);`
- `_ChallengeFailed(uint challengeID);`

Current:
```sol
event _ReparameterizationProposal(address proposer, string name, uint value, bytes32 propID);
event _NewChallenge(address challenger, bytes32 propID, uint pollID);
```

Proposed:
```sol
  event _ReparameterizationProposal(address proposer, string name, uint value, bytes32 propID);
  event _NewChallenge(address challenger, bytes32 propID, uint pollID);
+ event _ProposalAccepted(bytes32 propID);
+ event _ProposalUnprocessed(bytes32 propID);
+ event _ChallengeSucceeded(uint challengeID);
+ event _ChallengeFailed(uint challengeID);
+ event _RewardClaimed(address voter, uint challengeID, uint reward);
```

---

## PLCRVOTING

`PollCreated`: change args to `commitEndDate`, `revealEndDate`

Add: underscores for convention

Experimental:
`VoteRevealed`: change to `(voter, pollID, votesFor, votesAgainst)`

Current:
```sol
event VoteCommitted(address voter, uint pollID, uint numTokens);
event VoteRevealed(address voter, uint pollID, uint numTokens, uint choice);
event PollCreated(uint voteQuorum, uint commitDuration, uint revealDuration, uint pollID);
event VotingRightsGranted(address voter, uint numTokens);
event VotingRightsWithdrawn(address voter, uint numTokens);
```

Proposed:
```sol
_  event _VoteCommitted(address voter, uint pollID, uint numTokens);
*  event _VoteRevealed(address voter, uint pollID, uint votesFor, uint votesAgainst);
*  event _PollCreated(uint voteQuorum, uint commitEndDate, uint revealEndDate, uint pollID);
_  event _VotingRightsGranted(address voter, uint numTokens);
_  event _VotingRightsWithdrawn(address voter, uint numTokens);
```

**Comment by eccheung4** [comment]
Nice, looks good to me.

Not sure if challenger needs to be added to _Challenge event as I get that from the sender of transaction, but not against adding it.

**Comment by kangarang** [comment]
oh yeah, good point @eccheung4 . i do that too lol

**Comment by kangarang** [comment]
@eccheung4 , any particular thoughts on the experimental change?

`event _VoteRevealed(address voter, uint pollID, uint votesFor, uint votesAgainst);`

**Comment by kangarang** [comment]
maybe...

`event _VoteRevealed(uint pollID, uint numTokens, uint votesFor, uint votesAgainst);`

since `address voter` we can get from tx.from

**Comment by kangarang** [comment]
@eccheung4 

Here's another good one

Current:
```sol
event _ChallengeFailed(uint challengeID);
event _ChallengeSucceeded(uint challengeID);
```

Proposed:
```sol
event _ChallengeFailed(uint challengeID, uint rewardPool, uint totalTokens);
event _ChallengeSucceeded(uint challengeID, uint rewardPool, uint totalTokens);
```

**Comment by kangarang** [comment]
`_ProposalUnprocessed(bytes32 propID);`
->
`_ProposalExpired(bytes32 propID);`

**Comment by kangarang** [comment]
Resolved:

Registry: f5b42b26c7be4ae2a0f7756d6e079561a6a0b925

PLCRVoting: cab98ed1f8fb9746dd4f1afb7149bbd86db0f6fe

Parameterizer: 6d3eac7a54209dad485454bf26a907e1151b2d29

**Comment by kangarang** [comment]
Still need to add:

- `event _ChallengeSucceeded(uint challengeID, uint rewardPool, uint totalTokens);`
- `event _ChallengeFailed(uint challengeID, uint rewardPool, uint totalTokens);`
