### ISSUE TITLE
Invent schema for specifying the identifier property in _data

### ISSUE THREAD

**Issue by skmgoldin** [skmgoldin/tcr#7]
The purpose of the `_data` string in the `apply` function is for applicants to be able to furnish arbitrarily complex data related to their application. For example, an IPFS hash which resolves to:
```
{
  "name": "harvard",
  "average_student_debt": "10000 USD",
  "weather_in_locale": "poor"
}
```
In the TCR of top colleges, the identifier string here is that listed under the "name" property. The `_listingHash` should be `keccak256("harvard")`, and token-holders should strongly suspect they are being scammed if the supplied name does not match the supplied `_listingHash`.

A separate example could be:
```
{
  "domain": "consensys.net",
  "scamvoid_score": "high"
}
```
Here, the "domain" is the identifier string.

User interfaces should be able to flag to users when an _identifier_ in a `_data` object does not match the provided `_listingHash`. This will require some way of detecting what the _identifier_ property is. Perhaps for the purposes of user interfaces, by convention, an 'identifier' property in the `_data` object could be required?

**Comment by Shrugs** [comment]
Making the identifier constant `id` would be helpful. 

What's that multiurl spec that can use used to standardizing strings that include the information "if you support ipfs, here's the ipfs hash, otherwise here's a web url that responds in json" `mutli-url`? `multi-schema`? something like that

**Comment by hodkov** [comment]
Here is the IPFS file format for TCR items (in particular for TCR of TCRs) to the review.

# IPFS file format for TCR of TCRs items

File type: JSON.

    {
      "address": "0x81e1269708582ae17560b6acc0f45d0416df8d68",
      "name": "My TCR",
      "fields": [],
      "localization": {},
      "customization": {},
    }

* **address** - TCR contract address, required
* **name** - human-readable TCR name,
* **fields** - list of TCR item properties’ description (`Field`),
* **localization** - localization config,
* **customization** - ui customization config

## Field format
    {
      "name": "myProp",
      "type": "String",
      "default": "My property",
      "required": true
    }

* **name** - property name, string;
* **type** - property type, one of: `String`, `Number`, `Boolean`, `Any` or JSON object with Array or Object description (`ObjectType` or `ArrayType` format);
* **default** - default property value;
* **required** - boolean, is property required? 

### ObjectType format
    {
      "fields": []
    }
* **fields** - list of properties’ description - `Field` format

### ArrayType format
    {
      "type": {
        "fields": [
          {
            "name": "myProp",
            "type": "String",
            "default": "My property",
            "required": true
          }
        ]
      }
    }

* **type** - property type, one of: `String`, `Number`, `Boolean`, `Any` or JSON object with Array or Object description (`ObjectType` or `ArrayType` format);

## Localization format
    {
      "en": {
        "registryName": "My Super TCR",
        "apply": "Apply",
        "buy": "Buy",
        "candidate": "Candidate",
        "applicant": "Applicant",
        "tokenHolder": "Token holder",
      },
      "de": {
        ...
      },
      ...
    }

Object with properties - language codes. Every property contains key-value pairs of localized strings.

Open question: should we store localization config file to IPFS? Or should it be a link to a third-party service? IPFS over IPNS?

## Custiomization format
    {
      "defaultTextColor": "#000",
      "defaultFont": "Arial",
      "headerColor": "#FFF",
      ...
    }

An object with key-value pairs of ui properties.

Open question: should we store UIconfig to IPFS file? Or should it be a link to a third-party service?

**Comment by kangarang** [comment]
@Shrugs @skmgoldin  i prefer `identifier` over `id` only because it likely will not be a number. unless im missing something!

@hodkov thank you for posting those ipfs file formats. it's much larger than the scope of this issue; however this is still really great. i've been learning ipfs recently so it's nice to see it in the context of what i'm currently working on.

**Comment by kangarang** [comment]
@Shrugs i've been looking all over for what you mentioned, but still am not sure about it. was it [multiplexing](https://github.com/libp2p/specs/blob/master/7-properties.md#751-protocol-multiplexing)?

**Comment by kangarang** [comment]
@hodkov, i like the localization config. i dont feel think we need to store ui config data in ipfs. frontend apps can manage that in their build. the `Field` part is still a bit hazy to me. could you expand on that please? are fields the transaction arguments?

**Comment by Shrugs** [comment]
@kangarang honestly can't remember the name, it's very infuriating 😢

I'm not partial to `id` vs `identifier`, just as long as everything gets a guid of some sort

**Comment by kangarang** [comment]
After some thought, I actually prefer `id`. If we make it convention to use the keccak256 of the content's `data` as the content's `id`, it is quite a unique number.

```json
{
  "id": "0xab0d37198f6c323cc472eb6435b34943e99cff49fc9c765a0bc8fa7d09d087f0",
  "data": "AdToken"
}
```

**Comment by kangarang** [comment]
pseudocode:

```js
const listingString = 'AdToken'
const listingHash = keccak256(listingString)
// 0xab0d37198f6c323cc472eb6435b34943e99cff49fc9c765a0bc8fa7d09d087f0

const obj = {
  id: listingHash,
  data: listingString
}

const ipfsHash = ipfs.files.add(Buffer.from(JSON.stringify(obj)))
// ipfsHash: QmQBZmEJzdEujzo33P1L4KE25NFLMUJMTW9aNCwmcLx61o

registry.apply(listingHash, 50000, ipfsHash)

// mining...

// on the client side...

// event: _Application(listingHash, deposit, data)
// event: _Application('0xab0d37198f6c323cc472eb6435b34943e99cff49fc9c765a0bc8fa7d09d087f0', 50000, 'QmQBZmEJzdEujzo33P1L4KE25NFLMUJMTW9aNCwmcLx61o')

const eventResult = ['0xab0d37198f6c323cc472eb6435b34943e99cff49fc9c765a0bc8fa7d09d087f0', 50000, 'QmQBZmEJzdEujzo33P1L4KE25NFLMUJMTW9aNCwmcLx61o']

const listing = registry.listings.call(eventResult[0])
// listing: [applicationExpiry, whitelisted, owner, unstakedDeposit, challengeID]

const ipfsLink = ipfs.files.get(eventResult[2])

ipfsLink.forEach(file => {
  console.log(file.path)
  // QmQBZmEJzdEujzo33P1L4KE25NFLMUJMTW9aNCwmcLx61o
  console.log(file.content.toString('utf8'))
  // {"id":"0xab0d37198f6c323cc472eb6435b34943e99cff49fc9c765a0bc8fa7d09d087f0","data":"AdToken"}
})
```

**Comment by kangarang** [comment]
this is a decent start, but i need to dig deeper on IPLD merkle paths. i think that's where we'll find our answer.

**Comment by kangarang** [comment]
this is working. i feel good about this

**Comment by Kmoneal** [comment]
https://github.com/kangarang/tcr-ui/blob/master/docs/IPFS.md#prospect-park-ipfs-conventions
