### ISSUE TITLE
Has this project been audited?

### ISSUE THREAD

**Issue by derekchiang** [skmgoldin/tcr#73]
Sorry if this is not the right place to ask, but I was wondering to what extend have the smart contracts been audited?

**Comment by kangarang** [comment]
hi @derekchiang, thank you for asking. this is the right place. this smart contract system has been audited by [consensys diligence](https://consensys.net/diligence/). the audit began 

https://github.com/ConsenSys/tcr-audit

**Comment by kangarang** [comment]
hi @derekchiang, thank you for asking. this is the right place. this smart contract system has been audited by consensys diligence. [the audit](https://github.com/ConsenSys/tcr-audit) covered the codebase as of commit b2065612. The second phase review after their recommendations covered the codebase as of commit db40cd3c.

**Comment by derekchiang** [comment]
@kangarang Thanks for the prompt reply!  Happy that the project has been audited.

I recommend putting this info in the README since I imagine it's a common question from people who want to use this project in production.

**Comment by kangarang** [comment]
@derekchiang i agree, it is important and should be included in the readme as well as the owner's manual. thanks again for bringing this to our attention.

**Comment by blinky3713** [comment]
@kangarang Sorry, but I don't understand which is the commit that refers to the point in time where the audit was _complete_. By _complete_ I mean that the auditors gave you some concerns / requests, you fixed them, they gave you more etc. At some point the audit was completed in the sense that both parties were happy.

reading the audit report and your response above:
```
The audit covered the codebase as of commit b2065612. The second phase review after our recommendations covered the codebase as of commit db40cd3c.
```

Does this mean that both parties determined for the first time at commit db40cd3c that the audit was completed with satisfactory results. Or Is that commit where the second phase of the audit began after initial concerns were addressed, but it was not completed until a later commit?

Hope that question makes sense, thanks!

**Comment by skmgoldin** [comment]
https://github.com/ConsenSys/tcr-audit

@blinky3713 at db40cd3 both parties were happy. After that commit, all bets are off.

**Comment by blinky3713** [comment]
Awesome thanks! Can I suggest tagging this release so developers can find it more easily?

**Comment by kangarang** [comment]
@blinky3713 thanks for the suggestion. finally got around to tagging this badboy: https://github.com/skmgoldin/tcr/releases
