### ISSUE TITLE
Semantic improvements

### ISSUE THREAD

**Issue by kangarang** [skmgoldin/tcr#9]
It can be confusing to see what "reward" is referring to

`determineReward` CALL: get the number of tokens for the winning party of a *challenge* (**Applicant** or **Challenger**)
- suggestion: `getChallengeWinnerReward`

`voterReward` CALL: get the number of tokens for an individual **Voter** who *voted* in the `majority_bloc` of a challenge.
- suggestion: `getVoterReward`

`claimReward` SEND TX: transfer `voterReward` of `msg.sender` to `msg.sender`
- suggestion: `claimVoterReward`

`tokenClaims` CALL: see whether a **Voter** has tokens available to claim (i.e. did voter call `claimReward` yet)
- suggestions: `doesVoterHaveRewardToClaim`, `doesVoterHaveTokenClaims`

**Comment by kangarang** [comment]
Maybe we should change the language of "reward" to something else when talking about the number of tokens associated with **Applicant**/**Challenger** vs. the number of tokens associated with **Voters**

**Comment by skmgoldin** [comment]
My suggestions to your suggestions:
`getChallengeWinnerReward` -> `challengeWinnerReward`
`getVoterReward` -> `voterReward`

`doesVoterHaveRewardToClaim` -> `voterCanClaimReward`

I try to avoid `get` prefixes. Not a big deal though if it's important to you.

**Comment by kangarang** [comment]
+1 lgtm
